### ISSUE TITLE
EOFError in devise/passwords#create

### ISSUE THREAD

**Issue by watermarkchurch-deployment** [watermarkchurch/hymnal#1]
## Error in Hymnal

**EOFError** in **devise/passwords#create**
end of file reached

[View on Bugsnag](https://app.bugsnag.com/watermark-community-church/hymnal/errors/57f283b79496a22c1abd052a?event_id=57f283b7c5b7941100ea7445)
## Stacktrace

```
/opt/rbenv/versions/2.1.0/lib/ruby/2.1.0/net/protocol.rb:153 - read_nonblock
```

[View full stacktrace](https://app.bugsnag.com/watermark-community-church/hymnal/errors/57f283b79496a22c1abd052a?event_id=57f283b7c5b7941100ea7445)

**Comment by tpett** [comment]
Password reset requests are failing due to mail failing to send. It probably isn't configured correctly anymore. We'll need to look into how mail is supposed to be configured on Heroku and set it up with Mailgun.
