### ISSUE TITLE
Switch to Material Icons

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/hymnal#27]
> Hey Team,
> 
> I noticed a feature on the admin side of the worship app that isn’t available anymore and wondering if you could help us find it.
> 
> https://worship.watermark.org/users/sign_in
> 
> When you click on a song, you have the options to “add section” and “edit song,” but neither of those will allow you to actually edit the lyrics of a song.  We used to be able to edit all the individual sections(verse 1, Chorus, bridge, etc.) of a song but now it seems that adding a new section is the only option. 
> 
> There’s also a black banner at the top of the admin page that wasn’t always there and might be covering some other features as well. 
> 
> Thanks for your help!!
> 
> Jon

The link is still there it just has zero width:
![image.png](https://zube.io/files/watermarkchurch/f2bb5a1ba0e5b9abc52f51329211c4d5-image.png)

Using material icons would solve this problem

**Comment by jpowell** [comment]
Fixed in 1c518e9bd4113e62572228daaabf556e49ae9c93

Used font awesome CDN
